package CouponSystemBeans;

import java.util.Collection;
/**
 * Simple been class that represent customer object.
 * @author michael
 *
 */
public class Customer {
	
	private long id;
	private String custName;
	private String password;
	private Collection<Coupon> coupons;
	
	
	
	public Customer() {
		super();
	}

/**
 * Customer object constructor.
 * @param id - generated by DB. 
 * @param compName - Customer name must be specific for each Customer.
 * @param password
 */
	public Customer(String custName, String password) {
		super();
		this.custName = custName;
		this.password = password;
	}


	public long getId() {
		return id;
	}


	public void setId(long id) {
		this.id = id;
	}


	public String getCustName() {
		return custName;
	}


	public void setCustName(String custName) {
		this.custName = custName;
	}


	public String getPassword() {
		return password;
	}


	public void setPassword(String password) {
		this.password = password;
	}


	public Collection<Coupon> getCoupons() {
		return coupons;
	}


	public void setCoupons(Collection<Coupon> coupons) {
		this.coupons = coupons;
	}


	@Override
	public String toString() {
		return "Customer [id=" + id + ", custName=" + custName + ", password=" + password+ "]";
	}
	
	
	

}
